# I] Import and download

In [1]:
import pandas

In [2]:
input_file_directory = '/Users/kja11/OneDrive - Háskóli Íslands/PhD ATG7//0 in_silico/Python/1)data_input/'
output_file_directory = '/Users/kja11/OneDrive - Háskóli Íslands/PhD ATG7/0 in_silico/Python/3)output/'

In [13]:
path = output_file_directory + "ATG7/TCGA_GTEX/all_tissues/"
path2 = 'dataframes_for_input/'

In [8]:
%%time
# DL data ATG7 isoform expression
df_ATG7_Normal = pandas.read_csv(path+path2+'df_ATG7_Normal_all.csv', sep = ",")
df_ATG7_Primary = pandas.read_csv(path+path2+'df_ATG7_Primary_all.csv', sep = ",")

#remove Survival information
dfs = df_ATG7_Normal, df_ATG7_Primary
for df in dfs:
    df.drop(df.columns[[3, 4]], axis = 1, inplace = True)

print(df_ATG7_Normal.shape)
print(df_ATG7_Primary.shape)   

#create df with the two groups
df_ATG7_NormPrim = pandas.concat([df_ATG7_Normal, df_ATG7_Primary], axis=0)
print(df_ATG7_NormPrim.shape)
df_ATG7_NormPrim.head(2)

(5847, 17)
(8022, 17)
(13869, 17)
Wall time: 64.8 ms

,sample,Sample_Type,Primary_Site,ATG7,ATG7_1,ATG7_2,ATG7_3,ATG7_tpm,ATG7_1tpm,ATG7_2tpm,ATG7_3tpm,ATG7_prot_tot,ATG7_1perc,ATG7_2perc,ATG7_3perc,ATG7_1norm,ATG7_2norm
0,GTEX-ZTTD-0326-SM-57WFW,Normal Tissue,Muscle,5.085097,3.955992,2.641679,1.137484,32.944283,14.519306,5.240574,1.19997,20.959850,69.271996,25.002916,5.725088,0.440723,0.159074
1,GTEX-OXRO-1726-SM-3LK6C,Normal Tissue,Muscle,4.001888,2.821767,1.823465,0.000000,15.020948,6.070277,2.539302,0.00000,8.609579,70.506084,29.493916,0.000000,0.404121,0.169051

In [9]:
%%time
# DL data gene expression for Normal Tissue and Primary Tumors
path = output_file_directory + "dataframes_for_input/"
ensembl_normal_protcoding = pandas.read_csv(path+"ensembl_normal_protcoding_expr.tsv", sep = "\t")
ensembl_primary_protcoding = pandas.read_csv(path+"ensembl_primary_protcoding_expr.tsv", sep = "\t")

print(ensembl_normal_protcoding.shape)
print(ensembl_primary_protcoding.shape)

ensembl_primary_protcoding.head()

(7429, 19383)
(9185, 19383)
Wall time: 3min 52s

,sample,ENSG00000198888,ENSG00000198763,ENSG00000198804,ENSG00000198712,ENSG00000228253,ENSG00000198899,ENSG00000198938,ENSG00000198840,ENSG00000212907,...,ENSG00000160678,ENSG00000160679,ENSG00000143553,ENSG00000214193,ENSG00000196182,ENSG00000181817,ENSG00000116885,ENSG00000116898,ENSG00000119535,ENSG00000142694
0,TCGA-02-0047-01,12.920386,13.122162,14.013687,13.525222,13.843998,13.777803,13.403833,12.812500,13.418832,...,6.490222,5.827309,6.513364,2.443619,5.282026,6.072280,3.985485,5.569572,4.365281,4.724089
1,TCGA-02-0055-01,10.398268,10.778221,12.394768,12.389569,11.728425,11.941167,12.202506,11.014897,11.022793,...,6.019293,5.716474,6.084693,2.307414,4.399842,6.515045,3.860966,6.722909,4.654781,5.545689
2,TCGA-02-2483-01,11.694535,12.025246,13.115462,13.408733,13.628814,13.422831,13.443729,12.998576,11.940967,...,4.865893,6.380602,6.655963,1.035643,4.701003,6.079570,3.215637,6.306130,3.625293,4.073828
3,TCGA-02-2485-01,10.430545,10.518083,11.979057,11.614360,12.047740,11.772712,11.765314,10.914447,10.930739,...,5.138313,6.309783,6.574205,1.130945,4.563191,6.101149,3.840955,6.224800,2.825804,3.810465
4,TCGA-04-1331-01,14.069484,14.629057,14.281572,14.285772,13.898994,14.339270,14.284872,13.664611,13.569319,...,8.902714,6.118692,5.581614,2.137535,4.390222,5.167957,3.933549,6.779479,2.042638,5.339833

# II] ATG7 isoforms + Whole gene expression (ensembl)

In [10]:
#Preparation of the global dataframe with ATG7 isoform expression AND whole gene expression
data = [[ensembl_normal_protcoding, df_ATG7_Normal], [ensembl_primary_protcoding, df_ATG7_Primary]]

df_final = []

for df in data:
    #Merge the two df to have ATG7 isoform expression + whole gene expression 
  df_merged = pandas.merge(df[1], df[0], on= 'sample')

  #delete the sample column and select column
  df_merged = df_merged.drop("sample", 1)
  df_merged = df_merged.drop(df_merged.columns[5:19], axis=1)
  
  #save in list
  df_final.append(df_merged)

ensembl_normal_protcoding_atg7_expr = df_final[0]
ensembl_primary_protcoding_atg7_expr = df_final[1]

print(ensembl_normal_protcoding_atg7_expr.shape)
print(ensembl_primary_protcoding_atg7_expr.shape)
ensembl_normal_protcoding_atg7_expr.head()

(5847, 19384)
(8022, 19384)

,Sample_Type,Primary_Site,ATG7,ATG7_1,ATG7_2,ENSG00000198712,ENSG00000228253,ENSG00000198899,ENSG00000198938,ENSG00000198840,...,ENSG00000160678,ENSG00000160679,ENSG00000143553,ENSG00000214193,ENSG00000196182,ENSG00000181817,ENSG00000116885,ENSG00000116898,ENSG00000119535,ENSG00000142694
0,Normal Tissue,Muscle,5.085097,3.955992,2.641679,14.445365,15.097141,14.472063,14.768352,13.814400,...,2.981848,5.677832,5.063070,2.901118,4.588581,5.141228,2.601721,6.100164,6.502089,5.015268
1,Normal Tissue,Muscle,4.001888,2.821767,1.823465,13.821200,14.816150,14.110781,14.703554,13.277745,...,9.067289,5.997733,5.158236,2.217237,4.671302,5.053079,2.370170,5.810708,2.124335,4.707639
2,Normal Tissue,Muscle,3.950379,2.792620,1.883517,14.062284,15.589729,14.877448,14.545960,13.778903,...,9.227606,5.525729,5.617656,0.790754,5.691266,6.396905,2.792876,7.330383,2.021477,1.978191
3,Normal Tissue,Muscle,3.756766,2.352930,1.589822,14.152279,15.603129,14.957645,14.132380,13.885395,...,9.563806,6.063118,5.653030,0.948623,7.323129,6.529981,2.053104,6.799101,2.277958,2.192172
4,Normal Tissue,Muscle,3.704980,2.540744,2.295295,14.262573,15.421933,14.876148,14.429965,13.765204,...,8.513948,6.009251,5.306292,1.104343,5.907119,5.832418,2.185847,6.858078,1.735488,2.761269

In [14]:
#save to csv
ensembl_normal_protcoding_atg7_expr.to_csv(path+path2+'ensembl_normal_atg7_proteinGE.tsv',sep = "\t", index=False)
ensembl_primary_protcoding_atg7_expr.to_csv(path+path2+'ensembl_primary_atg7_proteinGE.tsv',sep = "\t", index=False)

## B) ATG7 isoforms + Whole gene expression (symbol)

In [18]:
# %%time
# # DL data gene expression for Normal Tissue and Primary Tumors
# path = output_file_directory + "/ATG7/dataframes_for_input/"
# symbol_normal_protcoding = pandas.read_csv(path+"symbol_normal_protcoding_expr.tsv", sep = "\t")
# symbol_primary_protcoding = pandas.read_csv(path+"symbol_primary_protcoding_expr.tsv", sep = "\t")

# print(symbol_normal_protcoding.shape)
# print(symbol_primary_protcoding.shape)

# symbol_primary_protcoding.head()

(7429, 19190)
(9185, 19190)

,sample,MT-ND1,MT-ND2,MT-CO1,MT-CO2,MT-ATP8,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,...,S100A1,CHTOP,SNAPIN,SH3D21,STK40,LSM10,OSCP1,MRPS15,CSF3R,EVA1B
0,TCGA-02-0047-01,12.9202,13.1220,14.0136,13.5251,13.8439,13.7777,13.4037,12.8123,13.4187,...,6.4741,5.8017,6.4975,2.1509,5.2445,6.0507,3.8915,5.5389,4.2936,4.6685
1,TCGA-02-0055-01,10.3972,10.7774,12.3945,12.3893,11.7280,11.9408,12.2022,11.0142,11.0221,...,5.9969,5.6888,6.0633,1.9822,4.3299,6.4992,3.7582,6.7092,4.5964,5.5145
2,TCGA-02-2483-01,11.6941,12.0249,13.1153,13.4086,13.6287,13.4227,13.4436,12.9984,11.9406,...,4.8156,6.3632,6.6416,0.0718,4.6445,6.0581,3.0515,6.2878,3.5035,3.9856
3,TCGA-02-2485-01,10.4295,10.5171,11.9787,11.6139,12.0474,11.7723,11.7649,10.9137,10.9300,...,5.0968,6.2915,6.5590,0.2522,4.5009,6.0800,3.7367,6.2054,2.6067,3.7039
4,TCGA-04-1331-01,14.0694,14.6290,14.2815,14.2857,13.8989,14.3392,14.2848,13.6645,13.5692,...,8.8997,6.0978,5.5512,1.7660,4.3198,5.1273,3.8360,6.7663,1.6420,5.3038

In [19]:
# #Preparation of the global dataframe with ATG7 isoform expression AND whole gene expression
# data = [[symbol_normal_protcoding, df_ATG7_Normal], [symbol_primary_protcoding, df_ATG7_Primary]]

# df_final = []

# for df in data:
#     #Merge the two df to have ATG7 isoform expression + whole gene expression 
#   df_merged = pandas.merge(df[1], df[0], on= 'sample')

#   #delete the sample column and select column
#   df_merged = df_merged.drop("sample", 1)
#   df_merged = df_merged.drop(df_merged.columns[5:19], axis=1)
  
#   #save in list
#   df_final.append(df_merged)

# symbol_normal_protcoding_atg7_expr = df_final[0]
# symbol_primary_protcoding_atg7_expr = df_final[1]

# print(symbol_normal_protcoding_atg7_expr.shape)
# print(symbol_primary_protcoding_atg7_expr.shape)
# symbol_normal_protcoding_atg7_expr.head()

(7429, 19194)
(9185, 19194)

,Sample_Type,Primary_Site,ATG7_x,ATG7_1,ATG7_2,MT-ND1,MT-ND2,MT-CO1,MT-CO2,MT-ATP8,...,S100A1,CHTOP,SNAPIN,SH3D21,STK40,LSM10,OSCP1,MRPS15,CSF3R,EVA1B
0,Normal Tissue,Muscle,5.042,3.860,2.390,14.0639,13.9595,13.8503,14.4453,15.0971,...,2.7868,5.6494,5.0193,2.6940,4.5274,5.0998,2.3423,6.0790,6.4861,4.9700
1,Normal Tissue,Muscle,4.252,2.322,1.956,13.9265,13.5455,15.2642,14.3855,15.1867,...,9.3501,6.1104,6.0570,1.1770,6.8792,6.4325,2.1013,6.7035,1.1706,1.3167
2,Normal Tissue,Muscle,3.909,2.602,1.345,14.2878,14.1511,14.3722,13.8211,14.8161,...,9.0646,5.9750,5.1173,1.8683,4.6136,5.0090,2.0604,5.7848,1.7489,4.6514
3,Normal Tissue,Muscle,3.854,2.568,1.428,13.8853,14.2716,15.1167,14.0622,15.5897,...,9.2252,5.4941,5.5880,-0.4521,5.6631,6.3797,2.5683,7.3214,1.6140,1.5563
4,Normal Tissue,Muscle,3.822,2.164,1.293,12.9986,13.7570,14.4661,13.4082,14.0564,...,8.9779,6.1502,5.1330,2.0289,6.8202,6.1789,1.8524,6.7685,2.8838,1.8323

In [20]:
# #Why ATG7_x ?
# verif = symbol_normal_protcoding_atg7_expr[symbol_normal_protcoding_atg7_expr.columns[pandas.Series(symbol_normal_protcoding_atg7_expr.columns).str.startswith('ATG7')]]
# print(verif.head(2))

   ATG7_x  ATG7_1  ATG7_2  ATG7_y
0   5.042   3.860   2.390  5.0418
1   4.252   2.322   1.956  4.2518

In [21]:
# data = [symbol_normal_protcoding_atg7_expr, symbol_primary_protcoding_atg7_expr]

# for df in data:
#     df.drop('ATG7_y', axis = 1, inplace=True) 
#     df.rename(columns = {'ATG7_x' : 'ATG7'}, inplace=True)
#     verif = df[df.columns[pandas.Series(df.columns).str.startswith('ATG7')]]
#     print(verif.head(2))

    ATG7  ATG7_1  ATG7_2
0  5.042   3.860   2.390
1  4.252   2.322   1.956
    ATG7  ATG7_1  ATG7_2
0  4.824   3.239   1.903
1  4.790   4.056   1.151

In [22]:
# #save to csv

# symbol_normal_protcoding_atg7_expr.to_csv(path+path2+'symbol_normal_atg7_ProteinGE.tsv',sep = "\t", index=False)
# symbol_primary_protcoding_atg7_expr.to_csv(path+path2+'symbol_primary_atg7_ProteinGE.tsv',sep = "\t", index=False)